### ISSUE TITLE
Compile error "no `EventLoop` in the root"

### ISSUE THREAD

**Issue by andybalaam** [tdfischer/pto#68]
I get lots of compile errors when I try to compile on Ubuntu 18.04.  Am I doing something wrong?

```$ uname -a
Linux myhost 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ rustc --version
rustc 1.24.1
$ cargo --version
cargo 0.26.0
$ cargo build
   Compiling pto v0.3.0 (file:///home/andrebal/code/pto)
error[E0432]: unresolved import `mio::EventLoop`
  --> src/bridge.rs:22:11
   |
22 | use mio::{EventLoop,Handler,Token,EventSet,PollOpt,Sender};
   |           ^^^^^^^^^ no `EventLoop` in the root

error[E0432]: unresolved import `mio::Handler`
  --> src/bridge.rs:22:21
   |
22 | use mio::{EventLoop,Handler,Token,EventSet,PollOpt,Sender};
   |                     ^^^^^^^ no `Handler` in the root
... lots more
```

**Comment by ara4n** [comment]
hi andy - pto is dead alas; you will want to hack on https://github.com/matrix-org/matrix-ircd instead (which is distantly forked from it).

**Comment by andybalaam** [comment]
Thanks - can I suggest modifying the readme and/or github description to indicate deadness?

**Comment by ara4n** [comment]
i would if i could - @tdfischer perhaps you can update the readme? 😇
